#server (eureka 默认端口为：8761)
server:
  port: 8761

#spring
spring:
  application:
    name: erueka

#eureka
eureka:
  client:
    #是否注册到eureka
    #在默认设置下,该服务注册中心也会将自己作为客户端来尝试注册它自己
    register-with-eureka: true

    #是否从eureka获取注册信息
    fetch-registry: false
    
    availability-zones:   
      YouYuan: YouYuanZone
        
    service-url:
      YouYuanZone:  http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone:  http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    metadataMap:
      zone: YouYuanZone
      user: ${security.user.name}
      password: ${security.user.password}

  #指定环境
  environment: dev
  #指定数据中心  
  datacenter: YouYuan
  
  #关闭自我保护模式
  server:
    enable-self-preservation: false

    #设置清理无效节点的时间间隔，默认60000，即是60s
    eviction-interval-timer-in-ms: 60000

#服务认证
security:
  basic:
    enabled: true
  user:
    name: YouYuan
    password: 123456

management:
  security:
    enabled: false
